const ADD_PLANT = 'ADD_PLANT'
const EDIT_PLANT = 'EDIT_PLANT'
const DELETE_PLANT = 'DELETE_PLANT'
const STORE_PLANTS = 'STORE_PLANTS'
const READ_PLANTS = 'READ_PLANTS'
const TRIGGER_WATER_NOTIFICATION = 'TRIGGER_WATER_NOTIF'
const HANDLE_WATER_NOTIFICATION = 'HANDLE_WATER_NOTIFICATION'

export { ADD_PLANT, EDIT_PLANT, DELETE_PLANT, TRIGGER_WATER_NOTIFICATION, HANDLE_WATER_NOTIFICATION, STORE_PLANTS, READ_PLANTS };